title: Your awesome title
author: GitHub User
email: SteveDuncan@webdevpros.org
description: > # this means to ignore newlines until "baseurl:"
  Showcase practice projects, exercises and algorithms.

# social links
github_username:  Steve-Duncan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
